export const SET_LOADED_CARS = 'SET_LOADED_CARS'
export const SET_LOADED_CITIES = 'SET_LOADED_CITIES'
export const SET_LOADED_POINTS = 'SET_LOADED_POINTS'
export const SET_LOADED_CATEGORIES = 'SET_LOADED_CATEGORIES'
export const SET_LOADED_RATES = 'SET_LOADED_RATES'

export const CHANGE_CITY = 'CHANGE_CITY'
export const CHANGE_POINT = 'CHANGE_POINT'
export const SET_CHOOSE_CAR = 'SET_CHOOSE_CAR'

export const SET_LOCATION = 'SET_LOCATION'
export const SET_CORDINATE_CITY = 'SET_CORDINATE_CITY'
export const SET_CONFIRM_CITY = 'SET_CONFIRM_CITY'

export const SET_LOADING = 'SET_LOADING'
export const SET_ERROR = 'SET_ERROR'